### ISSUE TITLE
Feature request - add menu entry to reload

### ISSUE THREAD

**Issue by yafp** [sorax/plugin.video.sandmann#1]
It would be helpful if a user could easily reload via menu or shortcut to get the video-reference updated.

Background: my son watches sandmann each night, on the following day the plugin might be still in foreground and still showing the episode from the last day.
righr now i have to navigate away into another kodi section - and then return to your plugin to force a reload.

**Comment by sorax** [comment]
Hi @yafp, thanks so much for your feedback!
I have the same issue :-) and I am working on a solution.
A new version should be available soon.

**Comment by sorax** [comment]
Update is ready and submitted to the Kodi Addon Maintainers.
You can watch the current state here if you like: https://github.com/xbmc/repo-plugins/pull/2628

**Comment by yafp** [comment]
@sorax thanks

**Comment by sorax** [comment]
Finally the PR was merged into the Plugin-Repo.
So the update should be available within Kodi tomorrow (23.12.2019).
