### ISSUE TITLE
Kodi 19 Kompatibilität

### ISSUE THREAD

**Issue by chefmagier** [sorax/plugin.video.sandmann#4]
Hallo,
Das seeehr wichtige Plugin wird leider von Kodi 19 auf disabled gesetzt.
Vermutlich wegen Python3?
Mit der Bitte um Update :)
Daniel

**Comment by handfrog** [comment]
+1

**Comment by handfrog** [comment]
Ich bin bestimmt kein Python-Experte, konnte es aber mit diesen kleinen Änderungen zum laufen bringen:
Tested on ArchLinux (Python version: 3.9.2)

`--- ../plugin.video.sandmann-master/addon.xml	2020-03-03 20:20:24.000000000 +0100
+++ addon.xml	2021-03-28 01:51:12.392910267 +0100
@@ -2,10 +2,10 @@
 <addon
     id="plugin.video.sandmann"
     name="Sandmann"
-    version="1.2.1"
+    version="1.2.2+matrix"
     provider-name="sorax">
   <requires>
-    <import addon="xbmc.python" version="2.26.0" />
+    <import addon="xbmc.python" version="3.0.0" />
   </requires>
   <extension point="xbmc.python.pluginsource" library="addon.py">
     <provides>video</provides>`

`--- ../plugin.video.sandmann-master/addon.py	2020-03-03 20:20:24.000000000 +0100
+++ addon.py	2021-03-28 01:33:06.783686266 +0100
@@ -74,7 +74,7 @@
 
 
 if update == 0:
-    global refresh_timer
+    refresh_timer
     # xbmc.executebuiltin("Notification(%s, %s, %d, %s)" %
     #                     (addon_name, "Updating...", 5000, addon_icon))
     refresh_timer = Timer(interval * 60 * 60, reload)`

`--- ../plugin.video.sandmann-master/sandmann.py	2020-03-03 20:20:24.000000000 +0100
+++ sandmann.py	2021-03-28 01:42:55.228710592 +0100
@@ -17,15 +17,12 @@
 
 import json
 
-try:
-    from html.parser import HTMLParser
-    from urllib.request import urlopen
-except ImportError:
-    from HTMLParser import HTMLParser
-    from urllib2 import urlopen
-
+from html import unescape
+from urllib.request import urlopen
+ 
 import xbmcaddon
 
+
 addon = xbmcaddon.Addon()
 
 
@@ -35,8 +32,7 @@
 
 
 def sanitize(text):
-    h = HTMLParser()
-    return h.unescape(text)
+    return unescape(text)
 
 
 def getTitle(content, dgs):`

**Comment by handfrog** [comment]
I was able to run on kodi matrix, with the following changes:

```diff
--- ../plugin.video.sandmann-master/addon.xml	2020-03-03 20:20:24.000000000 +0100
+++ addon.xml	2021-03-28 01:51:12.392910267 +0100
@@ -2,10 +2,10 @@
 <addon
     id="plugin.video.sandmann"
     name="Sandmann"
-    version="1.2.1"
+    version="1.2.2+matrix"
     provider-name="sorax">
   <requires>
-    <import addon="xbmc.python" version="2.26.0" />
+    <import addon="xbmc.python" version="3.0.0" />
   </requires>
   <extension point="xbmc.python.pluginsource" library="addon.py">
     <provides>video</provides>
```
```diff
--- ../plugin.video.sandmann-master/addon.py	2020-03-03 20:20:24.000000000 +0100
+++ addon.py	2021-03-28 01:33:06.783686266 +0100
@@ -74,7 +74,7 @@
 
 
 if update == 0:
-    global refresh_timer
+    refresh_timer
     # xbmc.executebuiltin("Notification(%s, %s, %d, %s)" %
     #                     (addon_name, "Updating...", 5000, addon_icon))
     refresh_timer = Timer(interval * 60 * 60, reload)
```
```diff
--- ../plugin.video.sandmann-master/sandmann.py	2020-03-03 20:20:24.000000000 +0100
+++ sandmann.py	2021-03-28 01:42:55.228710592 +0100
@@ -17,15 +17,12 @@
 
 import json
 
-try:
-    from html.parser import HTMLParser
-    from urllib.request import urlopen
-except ImportError:
-    from HTMLParser import HTMLParser
-    from urllib2 import urlopen
-
+from html import unescape
+from urllib.request import urlopen
+ 
 import xbmcaddon
 
+
 addon = xbmcaddon.Addon()
 
 
@@ -35,8 +32,7 @@
 
 
 def sanitize(text):
-    h = HTMLParser()
-    return h.unescape(text)
+    return unescape(text)
 
 
 def getTitle(content, dgs):
```

tested running kodi 19.0-9 on archlinux
python version: 3.9.2

There are changes in python 3.4 (see [here](https://stackoverflow.com/questions/2360598/how-do-i-unescape-html-entities-in-a-string-in-python-3-1)) so perhaps you should catch the ImportError for older python3 versions again.

**Comment by sorax** [comment]
I'll have a look - thank you!

**Comment by sorax** [comment]
PR: https://github.com/xbmc/repo-plugins/pull/3819
