### ISSUE TITLE
Switch to MDR / KiKa URL

### ISSUE THREAD

**Issue by handfrog** [sorax/plugin.video.sandmann#6]
I updated my main system (were the kids watch) to kodi 19.3 (LE10.0.01) the day before yesterday so I had to invest some time in order to use the plugin again: https://github.com/handfrog/plugin.video.sandmann/commit/9aaca9fa015af07da30123910c8cce4d059dccfd

On the way I realised that the [MDR / KiKa](https://www.ardmediathek.de/sendung/unser-sandmaennchen/Y3JpZDovL21kci5kZS9zZW5kZXJlaWhlbi84NjY2ZjI5OS02ZGU3LTQwNjMtODY4MS01NjA5ZWVlMzI4OGU/?isChildContent) version of the show offers easier to handle titles: https://appdata.ardmediathek.de/appdata/servlet/tv/Sendung?documentId=11094342&json
(The next days I also wanted to checkout https://api.ardmediathek.de/, perhaps there are even more possiblities.)

Also my kids didn't like the evil giants on 24th show, and the kika version was more harmless. 😅 

Honestly I also did not get, why some times only dgs versions were picked even with dgs switch in addon settings set to false.
My guess is the dgs version is not always the uneven one so getEpisodeData returns wrong data: https://github.com/sorax/plugin.video.sandmann/blob/10ded16524b3310c707dbba128172483dcb0cd6b/sandmann.py#L106

Switching to the mdr show version fixed this issue for me, too, as there are no dgs versions available.

What do you think about that idea?

Another idea is to add a settings switch for the show version such as an rbb / mdr switch, were rbb offers the dgs switch again.

Originally I wanted to submit this as PR to https://github.com/sorax/plugin.video.sandmann/issues/4 with the above linked code, but you were faster today 😄

**Comment by sorax** [comment]
hi @handfrog,
first of all: thank you for your comment and the ideas you are investing - I really appreciate that!

the feed / data-source I'm currently using has the described issue. back then I just scraped the url out of the ardmediathek-website and tried to parse it. this did work for quite a while. but for some month the dgs and non-ddgs versions are mixed and I hat do enable the dgs version in the addon-settings to manually pick the correct version based on the shown preview image.

I myself prefer the rbb-version of the sandmann episodes and I think this is the version shown on sandman.de as well (please correct me I I'm wrong here).

but I understand your request for having: 
- a working filter for dgs-version 
- the option to pick/switch the source ([rbb-version](https://www.ardmediathek.de/sendung/sandmann/Y3JpZDovL3JiYi1vbmxpbmUuZGUvc2FuZG1hbm4/?isChildContent) or [mdr-version](https://www.ardmediathek.de/sendung/unser-sandmaennchen/Y3JpZDovL21kci5kZS9zZW5kZXJlaWhlbi84NjY2ZjI5OS02ZGU3LTQwNjMtODY4MS01NjA5ZWVlMzI4OGU/?isChildContent))

yesterday I wrote an email to api@ard.de and requested developer access to their api. hopefully we'll find an easier way to get the episodes from the mediathek. I did start working on v2 of the plugin and I would love to have a valid and stable data-source and and someone for beta-testing, feature-requests an cool ideas ;-)

**Comment by sorax** [comment]
The ARD answered to my email:

> Vielen Dank für Ihr Interesse an der Nutzung der ARD Core-API.
> Leider kann ich eine Freischaltung Ihrer E-Mail-Adresse zum jetzigen Zeitpunkt nicht vornehmen, da diese API derzeit nur zu ARD-internen Gebrauch vorgesehen ist. Sollte sich dies jedoch ändern, werden wir dies unter developer.ard.de kundtun.

So for now we don't have a stable API to use.
Maybe we can collect all different possible data-sources and decide together what to use?

**Comment by sorax** [comment]
on top of the v2 (with the new/changed api) I was able to add a setting to choose which version of the Sandmann episodes is prefered (from **rbb** or **MDR**)
stay tuned for the new version

**Comment by sorax** [comment]
a new version (v2.1) will be available soon -> [Pull Request for Kodi 19](https://github.com/xbmc/repo-plugins/pull/3928)
this version will have a setting to switch between **rbb** or **mdr** as source for the episodes

**Comment by sorax** [comment]
The Sandman Addon (v2.1.0 for Leia and v2.1.1 for Matrix) now has an Option in the Addon-Settings to switch between the different sources (_rbb_ or _mdr_).

@handfrog Could you please have a look if this fits your needs? Thanks in advance.

**Comment by handfrog** [comment]
Sorry I did not answer. I have been very busy at work lately.
I tested it today on against Kodi 19.4 on my LibreElec 10.0.2 RPi 4, Windows 10 and ArchLinux and it works like a charm.

Thank you for your great work!

**Comment by sorax** [comment]
happy to hear that
